// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://clnjqpawethblkeziehb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsbmpxcGF3ZXRoYmxrZXppZWhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0MzM0MzQsImV4cCI6MjA2NTAwOTQzNH0.DFsb5MgV3Dz8gFqg6NXK0040c9XG7e3zIJIdG-qt7oQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);